
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header  from "./components/Layout/Header";
import Footer from "./components/Layout/Footer";
import { HeaderLink } from "./interfaces";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  // TODO: improve metadata for better seo
  title: "Land Helmets",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;

}>) {


  const headerLinks:HeaderLink[]=[
    {  
      title: "Home", 
      link: "/", 
      sublinks:[
        { title: "Lorem Ipsum", link: "/sub-item-1" },
        { title: "Lorem Ipsum", link: "/sub-item-2" },
      ],
      subtitle: "Lorem Ipsum is simply dummy text.",
      text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
      img:"/images/service.jpg"
    },
    {  
      title: "About Us", 
      link: "/about-us", 
      sublinks:[
        { title: "Lore Ipsum", link: "/sub-item-1" },
        { title: "Lore Ipsum", link: "/sub-item-2" },
      ],
      subtitle: "Lorem Ipsum is simply dummy text.",
      text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
      img:"/images/service.jpg"
    },
  ];

  return (
    <html className="min-w-[100vw] overflow-x-hidden" lang="en">
      <link rel="icon" href="./favicon.ico" sizes="any" />

      <body className={`min-w-[100vw] overflow-x-hidden	 ${inter.className}`}>
        <Header headerLinks={headerLinks} />
        {children}
        <Footer />
      </body>


    </html>
  );
}
