
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/Header";
import Footer from "./components/layout/Footer";
import { NavItems, SubNavItems } from "./interfaces";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  // TODO: improve metadata for better seo
  title: "Land Helmets",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;

}>) {


  const navItems: NavItems[] = [
    { title: "Home", link: "/" },
    { title: "About Us", link: "/about-us" },
  ];

  const subNavItems: SubNavItems[][] = [
    [
      { title: "Lore Ipsum", link: "/sub-item-1" },
      { title: "Lore Ipsum", link: "/sub-item-2" },
    ],
    [
      { title: "Lore Ipsum", link: "/sub-item-3" },
      { title: "Lore Ipsum", link: "/sub-item-4" },
    ]
  ];

  return (
    <html lang="en">
      <link rel="icon" href="./favicon.ico" sizes="any" />

      <Header navItems={navItems} subNavItems={subNavItems} />
      <body className={inter.className}>{children}</body>

      <Footer />
    </html>
  );
}
